### ISSUE TITLE
complaints from users indicating that the block does not match users showing the online user block

### ISSUE THREAD

**Issue by alexlittle** [alexlittle/moodle-block_online_users_map#10]

**Comment by diegomejia07** [comment]
I'm working on two different parts with Moodle.

1) Xampp to test locally with Moodle 2.6.8 and in block shows me the map but not the points where users are located .
2) I am working with Moodle 1.9.4 on a free hosting for testing and in this case only shows me the box and nothing else, or draw me a map and points ... The site URL is http : // pruebamoodle194 .besaba.com / .

The truth is not bad if I'm entering the key or the Google API key is bad or not , and not as Geonames enable web service nor how to use it . I would appreciate help me.

**Comment by diegomejia07** [comment]
I'm working on two different parts with Moodle.
1) Xampp to test locally with Moodle 2.6.8 and in block shows me the map but not the points where users are located .
2) I am working with Moodle 1.9.4 on a free hosting for testing and in this case only shows me the box and nothing else, or draw me a map and points ... The site URL is http : // pruebamoodle194 .besaba.com / .

The truth is not bad if I'm entering the key or the Google API key is bad or not , and not as Geonames enable web service nor how to use it . I would appreciate help me.

**Comment by diegomejia07** [comment]
![image](https://cloud.githubusercontent.com/assets/13982750/9504990/5451b26a-4c05-11e5-81a0-da2cc7446801.png)
